// ── PDF Service — Work Receipt + Loading Receipt ──────────
const PdfService = {

  // ── WORK RECEIPT (no loading data) ───────────────────────
  generateWork(work) {
    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = 210, margin = 20, cw = W - margin * 2;

      doc.setFillColor(249, 196, 0);
      doc.roundedRect(margin, 15, cw, 30, 4, 4, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(22); doc.setTextColor(26, 26, 26);
      doc.text('JCB WORKING', margin + 8, 27);
      doc.setFontSize(11); doc.setFont('helvetica', 'normal');
      doc.text('Work Receipt', margin + 8, 35);

      const invoiceNo = `#${String(work.id || 1).padStart(4, '0')}`;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(26, 26, 26);
      doc.text(`Invoice ${invoiceNo}`, margin, 55);
      doc.setFont('helvetica', 'normal');
      doc.text(fmtDate(work.date), W - margin, 55, { align: 'right' });

      doc.setDrawColor(224, 224, 224); doc.setLineWidth(0.4);
      doc.line(margin, 60, W - margin, 60);

      doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(120, 120, 120);
      doc.text('BILL TO', margin, 70);
      doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(26, 26, 26);
      doc.text(work.customerName, margin, 78);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(80, 80, 80);
      doc.text(work.village, margin, 85);
      if (work.mobileNumber) doc.text(`Mobile: ${work.mobileNumber}`, margin, 91);

      let y = 105;
      const addRow = (label, value, bold = false, vc = null) => {
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(100, 100, 100);
        doc.text(label, margin, y);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        doc.setTextColor(...(vc || [26, 26, 26]));
        doc.text(String(value), W - margin, y, { align: 'right' });
        doc.setTextColor(26, 26, 26); y += 8;
      };

      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(26, 26, 26);
      doc.text('WORK DETAILS', margin, y); y += 6;
      doc.setDrawColor(224, 224, 224); doc.line(margin, y, W - margin, y); y += 8;

      addRow('Date',                fmtDate(work.date));
      addRow('Start Time',          fmtTime(work.startTime));
      addRow('End Time',            fmtTime(work.endTime));
      addRow('Actual Working Time', fmtDuration(work.workingMinutes), false, [46, 125, 50]);
      if (work.breakMinutes > 0) addRow('Break Time', fmtDuration(work.breakMinutes), false, [230, 81, 0]);
      addRow('Hourly Rate', `Rs.${work.hourlyRate}/hr`);
      y += 4;

      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(26, 26, 26);
      doc.text('CHARGES', margin, y); y += 6;
      doc.setDrawColor(224, 224, 224); doc.line(margin, y, W - margin, y); y += 8;

      addRow('Work Amount', fmtCurrency(work.amount));
      if (work.dieselExpense > 0) {
        addRow('Diesel Expense', `-${fmtCurrency(work.dieselExpense)}`);
        addRow('Net Profit', fmtCurrency(work.profit || 0));
      }
      y += 2;
      addRow('Advance Received', fmtCurrency(work.advanceAmount || 0));
      addRow('Balance Due', fmtCurrency(work.balanceAmount || 0), true);
      y += 4;

      const pColor = work.paymentStatus === 'Paid' ? [46,125,50] : work.paymentStatus === 'Pending' ? [198,40,40] : [230,81,0];
      doc.setFillColor(...pColor);
      doc.roundedRect(margin, y, 54, 9, 2, 2, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(255, 255, 255);
      doc.text(`Payment: ${work.paymentStatus}`, margin + 4, y + 6);
      y += 18;

      doc.setFillColor(26, 26, 26);
      doc.roundedRect(margin, y, cw, 18, 4, 4, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(255, 255, 255);
      doc.text('TOTAL WORK AMOUNT', margin + 6, y + 11);
      doc.setFontSize(15); doc.setTextColor(249, 196, 0);
      doc.text(fmtCurrency(work.amount), W - margin - 6, y + 11, { align: 'right' });
      y += 26;

      if (work.notes) {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFont('helvetica', 'italic'); doc.setFontSize(9); doc.setTextColor(120, 120, 120);
        doc.text(`Notes: ${work.notes}`, margin, y);
      }

      doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(170, 170, 170);
      doc.text('Generated by JCB Working App', W / 2, 285, { align: 'center' });

      doc.save(`JCB_Work_${work.customerName.replace(/\s+/g,'_')}_${work.id || 'draft'}.pdf`);
      App.showToast('Work PDF downloaded!', 'success');
    } catch (err) {
      console.error('PDF error:', err);
      App.showToast('Could not generate PDF', 'error');
    }
  },

  // ── LOADING RECEIPT ───────────────────────────────────────
  generateLoading(record) {
    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = 210, margin = 20, cw = W - margin * 2;

      // Header
      doc.setFillColor(33, 150, 243);
      doc.roundedRect(margin, 15, cw, 30, 4, 4, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(22); doc.setTextColor(255, 255, 255);
      doc.text('JCB WORKING', margin + 8, 27);
      doc.setFontSize(11); doc.setFont('helvetica', 'normal');
      doc.text('Loading Receipt', margin + 8, 35);

      const recNo = `#L${String(record.id || 1).padStart(4, '0')}`;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(26, 26, 26);
      doc.text(`Loading ${recNo}`, margin, 55);
      doc.setFont('helvetica', 'normal');
      doc.text(fmtDate(record.date), W - margin, 55, { align: 'right' });

      doc.setDrawColor(224, 224, 224); doc.setLineWidth(0.4);
      doc.line(margin, 60, W - margin, 60);

      doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(120, 120, 120);
      doc.text('BILL TO', margin, 70);
      doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(26, 26, 26);
      doc.text(record.customerName, margin, 78);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(80, 80, 80);
      doc.text(record.village, margin, 85);
      if (record.customerMobile) doc.text(`Mobile: ${record.customerMobile}`, margin, 91);

      let y = 105;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(26, 26, 26);
      doc.text('VEHICLES & TRIPS', margin, y); y += 6;
      doc.setDrawColor(224, 224, 224); doc.line(margin, y, W - margin, y); y += 8;

      (record.vehicles || []).forEach(v => {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(26, 26, 26);
        doc.text(`${v.vehicleType} — ${v.vehicleNumber}`, margin, y); y += 6;
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(80, 80, 80);
        doc.text(`${v.trips} trips × Rs.${v.amountPerTrip}/trip`, margin + 4, y);
        doc.setFont('helvetica', 'bold'); doc.setTextColor(26, 26, 26);
        doc.text(fmtCurrency((v.trips || 0) * (v.amountPerTrip || 0)), W - margin, y, { align: 'right' });
        y += 10;
      });

      y += 2;
      doc.setDrawColor(200, 200, 200); doc.line(margin, y, W - margin, y); y += 6;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(100, 100, 100);
      doc.text('Total Trips', margin, y);
      doc.setTextColor(26, 26, 26);
      doc.text(String(record.totalTrips || 0), W - margin, y, { align: 'right' }); y += 10;

      const pColor = record.paymentStatus === 'Paid' ? [46,125,50] : record.paymentStatus === 'Pending' ? [198,40,40] : [230,81,0];
      doc.setFillColor(...pColor);
      doc.roundedRect(margin, y, 56, 9, 2, 2, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(255, 255, 255);
      doc.text(`Payment: ${record.paymentStatus}`, margin + 4, y + 6); y += 18;

      if (record.paidAmount > 0) {
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(100, 100, 100);
        doc.text('Amount Paid', margin, y); doc.setTextColor(76, 175, 80);
        doc.text(fmtCurrency(record.paidAmount), W - margin, y, { align: 'right' }); y += 8;
        doc.setTextColor(100, 100, 100);
        doc.text('Balance Due', margin, y); doc.setFont('helvetica', 'bold'); doc.setTextColor(198, 40, 40);
        doc.text(fmtCurrency(record.balanceDue || 0), W - margin, y, { align: 'right' }); y += 10;
      }

      doc.setFillColor(33, 150, 243);
      doc.roundedRect(margin, y, cw, 18, 4, 4, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(255, 255, 255);
      doc.text('TOTAL LOADING AMOUNT', margin + 6, y + 11);
      doc.setFontSize(15);
      doc.text(fmtCurrency(record.totalAmount || 0), W - margin - 6, y + 11, { align: 'right' });

      doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(170, 170, 170);
      doc.text('Generated by JCB Working App', W / 2, 285, { align: 'center' });

      doc.save(`JCB_Loading_${record.customerName.replace(/\s+/g,'_')}_${record.id || 'draft'}.pdf`);
      App.showToast('Loading PDF downloaded!', 'success');
    } catch (err) {
      console.error('Loading PDF error:', err);
      App.showToast('Could not generate PDF', 'error');
    }
  },

  // legacy alias so any old call still works
  generate(work) { return PdfService.generateWork(work); },
};
