// ── Share Service ─────────────────────────────────────────
const ShareService = {
  buildMessage(work) {
    return `🚧 *JCB WORK RECEIPT*
━━━━━━━━━━━━━━━━━
👤 *Customer:* ${work.customerName}
📍 *Village:* ${work.village}
📅 *Date:* ${fmtDate(work.date)}

⏰ *Start Time:* ${fmtTime(work.startTime)}
⏰ *End Time:* ${fmtTime(work.endTime)}
⏱️ *Duration:* ${fmtDuration(work.workingMinutes)}

💰 *Rate:* ₹${work.hourlyRate}/hr
💵 *Total Amount:* ${fmtCurrency(work.amount)}
${work.dieselExpense > 0 ? `⛽ *Diesel:* ${fmtCurrency(work.dieselExpense)}\n💹 *Profit:* ${fmtCurrency(work.profit || 0)}` : ''}
✅ *Payment:* ${work.paymentStatus}
${work.advanceAmount > 0 ? `💸 *Advance:* ${fmtCurrency(work.advanceAmount)}\n🔴 *Balance:* ${fmtCurrency(work.balanceAmount)}` : ''}
${work.notes ? `\n📝 *Notes:* ${work.notes}` : ''}
━━━━━━━━━━━━━━━━━
_Generated by JCB Working App_`;
  },

  whatsapp(work) {
    const msg  = ShareService.buildMessage(work);
    const encoded = encodeURIComponent(msg);
    const phone   = (work.mobileNumber || '').replace(/\D/g, '');
    const url = phone
      ? `https://wa.me/91${phone}?text=${encoded}`
      : `https://wa.me/?text=${encoded}`;
    window.open(url, '_blank');
  },

  async native(work) {
    const msg = ShareService.buildMessage(work);
    if (navigator.share) {
      try {
        await navigator.share({ title: 'JCB Work Receipt', text: msg });
      } catch (e) { /* user cancelled */ }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(msg);
      App.showToast('Receipt copied to clipboard!', 'success');
    }
  }
};
