// ── Share Service — Work + Loading ────────────────────────
const ShareService = {

  // ── WORK message (no loading data) ───────────────────────
  buildWorkMessage(work) {
    const breakLine = work.breakMinutes > 0
      ? `\n⏸️ *Break Time:* ${fmtDuration(work.breakMinutes)}`
      : '';
    return `🚧 *JCB WORK RECEIPT*
━━━━━━━━━━━━━━━━━
👤 *Customer:* ${work.customerName}
📍 *Village:* ${work.village}
📅 *Date:* ${fmtDate(work.date)}

⏰ *Start Time:* ${fmtTime(work.startTime)}
⏰ *End Time:* ${fmtTime(work.endTime)}
⏱️ *Working Time:* ${fmtDuration(work.workingMinutes)}${breakLine}

💰 *Rate:* ₹${work.hourlyRate}/hr
💵 *Total Work Amount:* ${fmtCurrency(work.amount)}
${work.dieselExpense > 0 ? `⛽ *Diesel:* ${fmtCurrency(work.dieselExpense)}\n💹 *Profit:* ${fmtCurrency(work.profit || 0)}` : ''}
✅ *Payment:* ${work.paymentStatus}
${work.advanceAmount > 0 ? `💸 *Advance:* ${fmtCurrency(work.advanceAmount)}\n🔴 *Balance:* ${fmtCurrency(work.balanceAmount)}` : ''}
${work.notes ? `\n📝 *Notes:* ${work.notes}` : ''}
━━━━━━━━━━━━━━━━━
_Generated by JCB Working App_`;
  },

  whatsappWork(work) {
    const msg     = ShareService.buildWorkMessage(work);
    const encoded = encodeURIComponent(msg);
    const phone   = (work.mobileNumber || '').replace(/\D/g, '');
    const url     = phone
      ? `https://wa.me/91${phone}?text=${encoded}`
      : `https://wa.me/?text=${encoded}`;
    window.open(url, '_blank');
  },

  // ── LOADING message ───────────────────────────────────────
  buildLoadingMessage(record) {
    const vehicles = (record.vehicles || []).map(v => {
      const total = (v.trips || 0) * (v.amountPerTrip || 0);
      return `${vIcon(v.vehicleType)} *${v.vehicleType} — ${v.vehicleNumber}*\n   ${v.trips} trips × ₹${v.amountPerTrip}/trip = ${fmtCurrency(total)}`;
    }).join('\n');

    return `📦 *JCB LOADING RECEIPT*
━━━━━━━━━━━━━━━━━
👤 *Customer:* ${record.customerName}
📍 *Village:* ${record.village}
📅 *Date:* ${fmtDate(record.date)}
${record.customerMobile ? `📞 *Mobile:* ${record.customerMobile}` : ''}

🚗 *VEHICLES & TRIPS*
${vehicles}

🔢 *Total Trips:* ${record.totalTrips || 0}
💵 *Total Loading Amount:* ${fmtCurrency(record.totalAmount || 0)}

✅ *Payment:* ${record.paymentStatus}
${record.paidAmount > 0 ? `💸 *Paid:* ${fmtCurrency(record.paidAmount)}\n🔴 *Balance:* ${fmtCurrency(record.balanceDue || 0)}` : ''}
━━━━━━━━━━━━━━━━━
_Generated by JCB Working App_`;
  },

  whatsappLoading(record) {
    const msg     = ShareService.buildLoadingMessage(record);
    const encoded = encodeURIComponent(msg);
    const phone   = (record.customerMobile || '').replace(/\D/g, '');
    const url     = phone
      ? `https://wa.me/91${phone}?text=${encoded}`
      : `https://wa.me/?text=${encoded}`;
    window.open(url, '_blank');
  },

  // legacy alias
  whatsapp(work) { return ShareService.whatsappWork(work); },
  buildMessage(work) { return ShareService.buildWorkMessage(work); },
};
